site_name: One Piece Wiki
site_url: https://otchitan.github.io/One-Piece-Wiki
plugins:
    - search
    - autorefs:
          resolve_closest: true
theme:
    name: material
    palette:
        scheme: default
        primary: custom
        accent: red
    features:
        - navigation.footer
extra_css:
    - stylesheets/extra.css
markdown_extensions:
    - attr_list
