site_name: One Piece Wiki
site_url: https://otchitan.github.io/One-Piece-Wiki
theme:
    name: material
    palette:
        scheme: default
        primary: custom
        accent: red
    features:
        - navigation.footer
extra_css:
    - stylesheets/extra.css
